### ISSUE TITLE
process-put: Wrong type argument: processp, nil

### ISSUE THREAD

**Issue by ahungry** [mallt/php-scratch#1]
I attempted to run some PHP code in the php-scratch buffer, and received the following error:

process-put: Wrong type argument: processp, nil

**Comment by mallt** [comment]
Did you accidentally kill the `"*php-scratch-repl*"` buffer? This is the buffer that's running the repl process. If you call <kbd>M-x</kbd> `php-scratch` again the buffer should be created again.

**Comment by ahungry** [comment]
Maybe it was because when I first attempted to run the command, the REPL failed to spawn, as I didn't have the boris binary defined in the variable that looks for it.

Boris-mode requires defining a similar variable (that holds the location of the boris binary) - maybe the default value for this project's variable should be set to what the boris one is?

**Comment by mallt** [comment]
Good suggestion, thanks! I've updated the default value of the variable.
